### ISSUE TITLE
Serializer encountered maximum depth

### ISSUE THREAD

**Issue by Eliakos** [valyala/fastjson#10]
Hello,

fastJSON is used by an ArarangoDB client driver ArangoDB-NET.
An issue has been opened there https://github.com/yojimbo87/ArangoDB-NET/issues/53 because apparently there is a blocking problem in fastJSON serialization.

Here is the problem i paste here :

Saved to restsharp, i retrieve some json data from a rest api source.
I do my stuff with the related objects then i want to store into arango.
For that i follow the doc https://github.com/yojimbo87/dictator#convert-strongly-typed-object-to-document.

And it works for very little objects as mostly i got this error :
"Serializer encountered maximum depth of 20"
I don't know what is this maximum depth but i imagined 20 is not big either so i changed this setting;

        ASettings.JsonParameters.SerializerMaxDepth = 255;

Apparently it's not enough as i get "Serializer encountered maximum depth of 255".

I looked at some objects, some were not so little so i loop them to do the same thing on each of their element instead of the whole structure but still the same error.

This drives me to think that "Convert strongly typed object to document" is OK but with very little object then...

**Comment by valyala** [comment]
@Eliakos , it looks like you need https://github.com/mgholam/fastJSON instead of `fastjson` :)
