### ISSUE TITLE
Dynamic json parsing

### ISSUE THREAD

**Issue by nikolas7892** [valyala/fastjson#13]
I'm working with an endpoint that is subject to dynamic updates in key and value pairs. What is the most efficient way to parse a nested json object in a json array without knowing the exact key, but knowing potential value characters? I had in mind to iterate over values and simply use switch / if clauses to match contained characters by key value until reaching the nested object. Is that the ideal solution?

**Comment by valyala** [comment]
> I had in mind to iterate over values and simply use switch / if clauses to match contained characters by key value until reaching the nested object. Is that the ideal solution?

Yes, this sounds like good solution.

**Comment by valyala** [comment]
Closing this issue, since it looks like it has been resolved
