### ISSUE TITLE
Parse big integers as `int64` instead of `float64` in order to avoid precision loss

### ISSUE THREAD

**Issue by ostronom** [valyala/fastjson#15]
This code:
```golang
jp := new(fastjson.Parser)
parsed, _ := jp.Parse(`{"a": 8838840643388017390}`)
fmt.Printf("AS INT = %d, AS FLOAT = %f\n", parsed.GetInt("a"), parsed.GetFloat64("a"))
```

produces this output:
```
AS INT = 8838840643388017664, AS FLOAT = 8838840643388017664.000000
```

Which is clearly wrong.

**Comment by valyala** [comment]
JSON numbers are represented as `float64` type inside `fastjson`. The number `8838840643388017390` cannot be represented as `float64` without precision loss. The majority of JSON parsers use `float64` for numbers, so they also suffer from this issue. Try working with this number in any modern web browser and you'll see they also loose precision.
I get the following in the lastest Chrome:
```
JSON.parse(`{"a": 8838840643388017390}`)
{a: 8838840643388018000}
```
See also [this question on StackOverflow](https://stackoverflow.com/questions/13502398/json-integers-limit-on-size).

**Comment by ostronom** [comment]
But github.com/buger/jsonparser works as expected in this case.

**Comment by valyala** [comment]
`jsonparser` tries parsing the number as `int64` before falling back to `float64`. Will try implementing it in `fastjson`.

**Comment by nvx** [comment]
On a 32bit machine this issue would be even more noticeable as int would be 32bit on that platform. Obviously changing the type of Int() would break backwards compatibility, but it's probably worth fixing that at the same time - perhaps a new Int64() function, retaining the existing behaviour for the Int() function would be safest to fix both at once.

Can you do a lazy parse storing it as a string or byte array and only parse it as a float64 or int64 when the relevant function is called? I can't see people calling Int() or Float64() over and over again on the same value, so it's not like there's much to gain from caching the result.

**Comment by valyala** [comment]
@nvx , thanks for nice suggestion. Implemented it and added Int64() for obtaining integer numbers exceeding float64 precision
