### ISSUE TITLE
UTF unescaping bug

### ISSUE THREAD

**Issue by nvx** [valyala/fastjson#17]
Simplest explanation is via a code example comparing fastjson to the stdlib encoding/json:

```
package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"github.com/valyala/fastjson"
)

func main() {
	raw := []byte(`"\ud83e\udd2d"`)

	var outDefault string
	err := json.Unmarshal(raw, &outDefault)
	if err != nil {
		panic(err)
	}

	var p fastjson.Parser
	v, err := p.ParseBytes(raw)
	if err != nil {
		panic(err)
	}

	outFastBytes, err := v.StringBytes()
	if err != nil {
		panic(err)
	}

	outFast := string(outFastBytes)

	fmt.Println(outDefault)
	fmt.Println(outFast)

	fmt.Println(hex.Dump([]byte(outDefault)))
	fmt.Println(hex.Dump(outFastBytes))
}
```

Which when run outputs:

```
🤭
��
00000000  f0 9f a4 ad                                       |....|

00000000  ef bf bd ef bf bd                                 |......|
```

The encoding/json output appears to be correct. It looks like the code difference is in UTF-16 surrogate pairs. The relevant snippit of code in encoding/json that handles this case is here: https://github.com/golang/go/blob/release-branch.go1.11/src/encoding/json/decode.go#L1286

**Comment by valyala** [comment]
@nvx , thanks for the bug report. The issue should be fixed now

**Comment by nvx** [comment]
My unit tests pass now for this case, cheers! I had implemented a workaround not expecting it to be fixed so fast, awesome work!
