### ISSUE TITLE
wrong .String() return 

### ISSUE THREAD

**Issue by tsingson** [valyala/fastjson#2]
one issue , like this :

```
package main

import (
	"fmt"

	"github.com/valyala/fastjson"
)

func main() {
	postByte := []byte(`{"name":"string","next":{"key":"value"}}`)
	var p fastjson.Parser
	v, _ := p.ParseBytes(postByte)

	name := v.Get("name").String()
	name_should_be := "string"
	fmt.Println(name, name_should_be)
	value := v.Get("next").Get("key").String()
	value_should_be := "value"
	fmt.Println(value, value_should_be)
}
```

go run main.go   

```
"string" string
"value" value
```

it's wrong result of fastjson in .String() func .

**Comment by valyala** [comment]
[Value.String](https://godoc.org/github.com/valyala/fastjson#Value.String) returns string representation of the underlying JSON value. String representation of a JSON string is quoted string. So it works as intended. You should use [Value.GetStringBytes](https://godoc.org/github.com/valyala/fastjson#Value.GetStringBytes) instead:

```go
name := v.GetStringBytes("name")
fmt.Println(name)

value := v.GetStringBytes("next", "key")
fmt.Println(value)
```

Added reference to `Value.StringBytes` from the documentation for `Value.String`.
