### ISSUE TITLE
how to iterating object with 'k-v mappings'?

### ISSUE THREAD

**Issue by mthhk** [valyala/fastjson#35]
example code:
```
jsonObj:=fastjson.MustParse(`{"key":"value"}`)
for key,value := range jsonObj.toMap() {
// .....
}

**Comment by misterr8472** [comment]
Did you find an answer to this? I'd also be interested in finding out.

**Comment by valyala** [comment]
@misterr8472 , use [Object.Visit](https://godoc.org/github.com/valyala/fastjson#Object.Visit) for iterating over object entries.

**Comment by misterr8472** [comment]
Thank you! Works a treat :)
