### ISSUE TITLE
Type for boolean

### ISSUE THREAD

**Issue by awishformore** [valyala/fastjson#36]
I was just wondering why the type returned for boolean is eithe `true` or `false`. It's not really in line with the data types for JSON, is it? Why doesn't it return `boolean` in that case?

**Comment by valyala** [comment]
This is just historical artifact :) It is impossible to change the behavior now due to backwards compatibility.

**Comment by awishformore** [comment]
Do you have plans to release a v2 where you fix it? :D

**Comment by valyala** [comment]
There are no such plans yet, since this change is too small for v2

**Comment by awishformore** [comment]
Of course. Alrighty then, thanks.
