### ISSUE TITLE
Loop over array?

### ISSUE THREAD

**Issue by Fenny** [valyala/fastjson#48]
Is this the correct way to loop over a json array?
Or is there a more efficient way?

```go
	values, err := json.Array()
	if err != nil {
		fmt.Println(err)
	}
	for i := 1; i < len(values); i++ {
		fmt.Println(values[i].GetInt("id"))
	}
```

**Comment by valyala** [comment]
You already referenced the most efficient way for looping over array. Only start the loop index (`i`) from 0 instead of 1. It is possible to use `for ... range` loop:
```go
for _, v := range values {
    // use v here
}
```

**Comment by Fenny** [comment]
Works like a charm, thanks for clearing this up.

Great library btw 👍
