### ISSUE TITLE
Parse exponent part

### ISSUE THREAD

**Issue by johnatannvmd** [valyala/fastjson#55]
I found that floats in exponential notation with a point after the last digit of the coefficient do not parse correctly, meanwhile `strconv.ParseFloat(s, 64)` do the job.

Passed:
```golang
// Fractional + exponent part
f("1e4", 1.e4)
f("-1E-10", -1.e-10)
```
Failed:
```golang
// Fractional + exponent part
f("1.e4", 1.e4)
f("-1.E-10", -1.e-10)
```

`ParseFloat` test case
```golang
n, _ := strconv.ParseFloat("11.e4", 64)
if n != 11.e4 {
	t.Fatalf("Unexpected result from \"11.e4\" got: %v, want: %v", n, 11.e4)
}
n, _ = strconv.ParseFloat("-11.E-10", 64)
if n != -11.e-10 {
	t.Fatalf("Unexpected result from \"-11.E-10\" got: %v, want: %v", n, -11.E-10)
}
```

**Comment by valyala** [comment]
Fixed this issue in 4e5b64ece32f7f617eae3c6986ce6388142994ca . The bugfix is available starting from [v1.5.1](https://github.com/valyala/fastjson/tree/v1.5.1).
