### ISSUE TITLE
What about adding more complex validation ?

### ISSUE THREAD

**Issue by yuriy-yarosh** [valyala/fastjson#7]
@valyala what do you think about adding more complex validation primitives like expected object keys, expected key value types ? It would be also great to be able to add some custom registrable validation func's - min/max for numbers, minLength / maxLength / regex for strings etc.

Basic stuff for a fail-fast strategy.

**Comment by valyala** [comment]
Complex validation is orthogonal to fast json parsing, so it is unlikely this functionality will be added to `fastjson`. There are other packages exist for complex validation such as [validator](https://github.com/go-playground/validator) and [gojsonschema](https://github.com/xeipuuv/gojsonschema). Probably it would be better adding ability to validate `fastjson` values into these packages.

**Comment by yuriy-yarosh** [comment]
Well, I'm developing a custom graphql golang server right now, and wanted to be able to pass the expected value constraints directly to the parser, like - "the next expected value is a string that should look like an email no more than 64 chars" etc. The idea is that backend simply can't get an invalid data and it's better just to fail as fast as possible.

I think that it's better for me to fork `fastjson` and add some GraphQL related stuff directly, with some partial rewrites/additions.

Thank you for your time, sorry for bothering.

p.s. I'm going to visit next golang Kyiv meetup, we could discuss it there ...

**Comment by valyala** [comment]
> I think that it's better for me to fork fastjson and add some GraphQL related stuff directly, with some partial rewrites/additions.

Sounds good! Then I can add a link to your project from `fastjson`'s README.md .
