### ISSUE TITLE
Ability to replace Object field names before MarshalTo

### ISSUE THREAD

**Issue by msample** [valyala/fastjson#8]
The addition of Value.MarshalTo to  fastjson opens the door for supporting transformation.

What do you think about supporting the ability to alter Object field names or even removing them or replacing their values?

**Comment by msample** [comment]
qntfy/kazaam and jsonparser seem to have this covered. Closing.  Thx for fastjson.

**Comment by valyala** [comment]
Re-opening the issue, since it may be considered as valid feature request

**Comment by phuslu** [comment]
+1, currently we use jsonparser to do it. It's nice if fastjson could.

**Comment by rdcloyi** [comment]
+1, I love fastjson after a try and benchmark with other implementations. But I do need the Object/Value to support DeleteKey and AddKeyValue/AppendKeyValue after I parsed a json from bytes (e.g. HTTP body). Otherwise I have use another package in my app.

**Comment by valyala** [comment]
Added [Set](https://godoc.org/github.com/valyala/fastjson#Value.Set) and [Del](https://godoc.org/github.com/valyala/fastjson#Value.Del) methods.
